/*
Hedera Mirror Node REST API

Testing BalancesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mirrorclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/nickpoorman/hedera-ingress/mirrorclient"
)

func Test_mirrorclient_BalancesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BalancesAPIService ListAccountBalances", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BalancesAPI.ListAccountBalances(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
