/*
Hedera Mirror Node REST API

The Mirror Node REST API offers the ability to query cryptocurrency transactions and account information from a Hedera managed mirror node.  Base url: [/api/v1](/api/v1)  OpenAPI Spec: [/api/v1/docs/openapi.yml](/api/v1/docs/openapi.yml)

API version: 0.89.0
Contact: mirrornode@hedera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mirrorclient

import (
	"encoding/json"
)

// checks if the CryptoAllowancesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CryptoAllowancesResponse{}

// CryptoAllowancesResponse struct for CryptoAllowancesResponse
type CryptoAllowancesResponse struct {
	Allowances []CryptoAllowance `json:"allowances,omitempty"`
	Links *Links `json:"links,omitempty"`
}

// NewCryptoAllowancesResponse instantiates a new CryptoAllowancesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCryptoAllowancesResponse() *CryptoAllowancesResponse {
	this := CryptoAllowancesResponse{}
	return &this
}

// NewCryptoAllowancesResponseWithDefaults instantiates a new CryptoAllowancesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCryptoAllowancesResponseWithDefaults() *CryptoAllowancesResponse {
	this := CryptoAllowancesResponse{}
	return &this
}

// GetAllowances returns the Allowances field value if set, zero value otherwise.
func (o *CryptoAllowancesResponse) GetAllowances() []CryptoAllowance {
	if o == nil || IsNil(o.Allowances) {
		var ret []CryptoAllowance
		return ret
	}
	return o.Allowances
}

// GetAllowancesOk returns a tuple with the Allowances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoAllowancesResponse) GetAllowancesOk() ([]CryptoAllowance, bool) {
	if o == nil || IsNil(o.Allowances) {
		return nil, false
	}
	return o.Allowances, true
}

// HasAllowances returns a boolean if a field has been set.
func (o *CryptoAllowancesResponse) HasAllowances() bool {
	if o != nil && !IsNil(o.Allowances) {
		return true
	}

	return false
}

// SetAllowances gets a reference to the given []CryptoAllowance and assigns it to the Allowances field.
func (o *CryptoAllowancesResponse) SetAllowances(v []CryptoAllowance) {
	o.Allowances = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CryptoAllowancesResponse) GetLinks() Links {
	if o == nil || IsNil(o.Links) {
		var ret Links
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoAllowancesResponse) GetLinksOk() (*Links, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CryptoAllowancesResponse) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Links and assigns it to the Links field.
func (o *CryptoAllowancesResponse) SetLinks(v Links) {
	o.Links = &v
}

func (o CryptoAllowancesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CryptoAllowancesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Allowances) {
		toSerialize["allowances"] = o.Allowances
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableCryptoAllowancesResponse struct {
	value *CryptoAllowancesResponse
	isSet bool
}

func (v NullableCryptoAllowancesResponse) Get() *CryptoAllowancesResponse {
	return v.value
}

func (v *NullableCryptoAllowancesResponse) Set(val *CryptoAllowancesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCryptoAllowancesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCryptoAllowancesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCryptoAllowancesResponse(val *CryptoAllowancesResponse) *NullableCryptoAllowancesResponse {
	return &NullableCryptoAllowancesResponse{value: val, isSet: true}
}

func (v NullableCryptoAllowancesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCryptoAllowancesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


