/*
Hedera Mirror Node REST API

The Mirror Node REST API offers the ability to query cryptocurrency transactions and account information from a Hedera managed mirror node.  Base url: [/api/v1](/api/v1)  OpenAPI Spec: [/api/v1/docs/openapi.yml](/api/v1/docs/openapi.yml)

API version: 0.89.0
Contact: mirrornode@hedera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mirrorclient

import (
	"encoding/json"
)

// checks if the ContractsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContractsResponse{}

// ContractsResponse struct for ContractsResponse
type ContractsResponse struct {
	Contracts []Contract `json:"contracts,omitempty"`
	Links *Links `json:"links,omitempty"`
}

// NewContractsResponse instantiates a new ContractsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContractsResponse() *ContractsResponse {
	this := ContractsResponse{}
	return &this
}

// NewContractsResponseWithDefaults instantiates a new ContractsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContractsResponseWithDefaults() *ContractsResponse {
	this := ContractsResponse{}
	return &this
}

// GetContracts returns the Contracts field value if set, zero value otherwise.
func (o *ContractsResponse) GetContracts() []Contract {
	if o == nil || IsNil(o.Contracts) {
		var ret []Contract
		return ret
	}
	return o.Contracts
}

// GetContractsOk returns a tuple with the Contracts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractsResponse) GetContractsOk() ([]Contract, bool) {
	if o == nil || IsNil(o.Contracts) {
		return nil, false
	}
	return o.Contracts, true
}

// HasContracts returns a boolean if a field has been set.
func (o *ContractsResponse) HasContracts() bool {
	if o != nil && !IsNil(o.Contracts) {
		return true
	}

	return false
}

// SetContracts gets a reference to the given []Contract and assigns it to the Contracts field.
func (o *ContractsResponse) SetContracts(v []Contract) {
	o.Contracts = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ContractsResponse) GetLinks() Links {
	if o == nil || IsNil(o.Links) {
		var ret Links
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractsResponse) GetLinksOk() (*Links, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ContractsResponse) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Links and assigns it to the Links field.
func (o *ContractsResponse) SetLinks(v Links) {
	o.Links = &v
}

func (o ContractsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContractsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Contracts) {
		toSerialize["contracts"] = o.Contracts
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableContractsResponse struct {
	value *ContractsResponse
	isSet bool
}

func (v NullableContractsResponse) Get() *ContractsResponse {
	return v.value
}

func (v *NullableContractsResponse) Set(val *ContractsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContractsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContractsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContractsResponse(val *ContractsResponse) *NullableContractsResponse {
	return &NullableContractsResponse{value: val, isSet: true}
}

func (v NullableContractsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContractsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


